language: objective-c
osx_image: xcode11.2

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace K+News.xcworkspace -scheme K+News -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.2.2'
